### PR TITLE
reset functionality added

### PR DESCRIPTION
**Pull request by justijndepover**
Added an argument to remove the defaults AppleInterfaceStyle key.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why?

**Comment by justijndepover** [comment]
Your code contains an error if you set the mode to Light or Dark. Once you've set a specific mode with your program, and you try to change it via system preferences, it leaves your system in a mixed state (hence the following issue: https://github.com/sindresorhus/dark-mode/issues/3)

With the added reset you can change the mode back to normal (before it was broken)

**Comment by sindresorhus** [comment]
I appreciate the pull request, but I went with fixing the problem for real.
See: https://github.com/sindresorhus/dark-mode/releases/tag/2.0.0

**Comment by chemzqm** [comment]
Thank god, the panda.app works.
Hope I didn't install this tool from homebrew.

**Pull request closed without merging**
